USE [master]
GO
ALTER DATABASE [SerialData] MODIFY FILE ( NAME = N'SerialData', SIZE = 16777216KB , FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [SerialData] MODIFY FILE ( NAME = N'SerialData_log', SIZE = 262144KB , MAXSIZE = UNLIMITED)
GO
